"""Generate host firewall rules that enforce per-tenant egress isolation.

Docker network isolation alone is not sufficient (plan Rule 3 / Phase 4): the
EC2 host firewall must guarantee that each tenant's Docker subnet can reach only
that tenant's allowed on-prem CIDRs (through its VPN) and nothing else — in
particular not another tenant's Docker subnet or on-prem network, and not the
instance metadata endpoint.

This service produces deterministic, idempotent ``iptables`` rules organised
into one chain per tenant (``TABLESCOPE-TENANT-<ID>``) jumped from Docker's
``DOCKER-USER`` chain (which Docker evaluates before its own per-network ACCEPT
rules, so the jump cannot be preempted), plus a systemd unit so the rules are
reapplied on boot. It only *generates*
text; applying it requires root on the host (done by an operator or a
privileged worker), never by the API container.
"""

from __future__ import annotations

from dataclasses import dataclass, field

METADATA_CIDR = "169.254.169.254/32"
FIREWALL_CONFIG_DIR = "/etc/tablescope/tenant-firewall.d"
FIREWALL_SCRIPT_PATH = "/usr/local/sbin/tablescope-apply-tenant-firewall.sh"
SYSTEMD_UNIT_PATH = "/etc/systemd/system/tablescope-tenant-firewall.service"


@dataclass(slots=True)
class TenantFirewallSpec:
    tenant_id: str
    docker_subnet_cidr: str
    chain: str
    allowed_onprem_cidrs: list[str]
    # Optional extra destinations (DNS/NTP/internal) the tenant may reach.
    extra_allowed_cidrs: list[str] = field(default_factory=list)


class TenantFirewallService:
    """Render iptables rules and systemd persistence for tenant isolation."""

    def render_tenant_chain(
        self,
        spec: TenantFirewallSpec,
        *,
        other_subnets: list[str],
        other_onprem_cidrs: list[str],
    ) -> list[str]:
        """Render the ordered iptables rules for a single tenant chain."""
        chain = spec.chain
        src = spec.docker_subnet_cidr
        lines: list[str] = [
            f"# --- Tenant {spec.tenant_id} ({src}) ---",
            f"iptables -N {chain} 2>/dev/null || iptables -F {chain}",
            # Jump traffic originating from this tenant subnet into its chain.
            # Use DOCKER-USER (evaluated before Docker's own FORWARD ACCEPT
            # rules) and INSERT so it sits ahead of any trailing RETURN.
            f"iptables -C DOCKER-USER -s {src} -j {chain} 2>/dev/null || " f"iptables -I DOCKER-USER -s {src} -j {chain}",
            # Allow return traffic for established flows.
            f"iptables -A {chain} -m state --state ESTABLISHED,RELATED -j ACCEPT",
        ]

        # Explicit cross-tenant denies first (defense in depth, also logged).
        for other in sorted(set(other_subnets)):
            if other == src:
                continue
            lines.append(
                f"iptables -A {chain} -d {other} -m limit --limit 5/min "
                f'-j LOG --log-prefix "TS-DROP-XTEN {spec.tenant_id}: "'
            )
            lines.append(f"iptables -A {chain} -d {other} -j DROP")
        for other in sorted(set(other_onprem_cidrs) - set(spec.allowed_onprem_cidrs)):
            lines.append(f"iptables -A {chain} -d {other} -j DROP")

        # Block the instance metadata endpoint.
        lines.append(f"iptables -A {chain} -d {METADATA_CIDR} -j DROP")

        # Allow this tenant's own on-prem CIDRs (the point of the VPN).
        for cidr in spec.allowed_onprem_cidrs:
            lines.append(f"iptables -A {chain} -d {cidr} -j ACCEPT")
        for cidr in spec.extra_allowed_cidrs:
            lines.append(f"iptables -A {chain} -d {cidr} -j ACCEPT")

        # Default deny for everything else this tenant tries to reach, logged.
        lines.append(f"iptables -A {chain} -m limit --limit 5/min " f'-j LOG --log-prefix "TS-DROP {spec.tenant_id}: "')
        lines.append(f"iptables -A {chain} -j DROP")
        # Drop an applied-marker the (containerized) control plane can read to
        # confirm the firewall ran, since it cannot inspect host iptables.
        lines.append(f"date -u +%Y-%m-%dT%H:%M:%SZ > {FIREWALL_CONFIG_DIR}/{spec.tenant_id}.applied")
        return lines

    def render_script(self, specs: list[TenantFirewallSpec]) -> str:
        """Render a full idempotent apply script for all tenants."""
        all_subnets = [s.docker_subnet_cidr for s in specs]
        all_onprem = [c for s in specs for c in s.allowed_onprem_cidrs]

        body: list[str] = [
            "#!/usr/bin/env bash",
            "# Generated by Tablescope tenant data-plane provisioner.",
            "# Applies per-tenant egress isolation. Idempotent; safe to re-run.",
            "set -euo pipefail",
            "",
            "# Ensure Docker's user hook chain exists before we jump from it.",
            "iptables -N DOCKER-USER 2>/dev/null || true",
            f"mkdir -p {FIREWALL_CONFIG_DIR}",
            "",
        ]
        for spec in specs:
            other_subnets = [s for s in all_subnets if s != spec.docker_subnet_cidr]
            other_onprem = [c for c in all_onprem if c not in spec.allowed_onprem_cidrs]
            body.extend(
                self.render_tenant_chain(
                    spec,
                    other_subnets=other_subnets,
                    other_onprem_cidrs=other_onprem,
                )
            )
            body.append("")
        return "\n".join(body) + "\n"

    def render_systemd_unit(self) -> str:
        """Render a systemd unit that applies tenant firewall rules at boot."""
        return f"""[Unit]
Description=Tablescope per-tenant firewall isolation
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={FIREWALL_SCRIPT_PATH}

[Install]
WantedBy=multi-user.target
"""
