"""Generate per-tenant Docker Compose files and the on-host directory layout.

The shared control plane (web-ui, platform-api, worker, postgres, redis) stays
in the base ``docker-compose.yml``. For each tenant we generate a *separate*
compose file that runs exactly one Teiid/WildFly container on the tenant's own
Docker network/subnet with a fixed IP, its own VDB directory and logs, its own
Teiid API key, and ports bound to ``127.0.0.1`` only (never published publicly).

Strict isolation rules enforced here (plan Phase 3):
  * one tenant network per file, with a fixed subnet
  * VDB/logs/secrets directories are tenant-specific and never shared
  * the Docker socket is never mounted into a tenant container
  * the container is not privileged
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from app.services.tenant_layout import TenantLayout

TEIID_IMAGE_DEFAULT = "tablescope-teiid:latest"


@dataclass(slots=True)
class GeneratedCompose:
    tenant_id: str
    compose_path: str
    content: str
    directories: list[str]


class TenantComposeService:
    """Render and (optionally) materialize per-tenant compose files."""

    def __init__(self, teiid_image: str | None = None) -> None:
        self._image = teiid_image or os.getenv("TENANT_TEIID_IMAGE", TEIID_IMAGE_DEFAULT)

    def render(self, layout: TenantLayout) -> str:
        """Render the tenant compose file as a YAML string."""
        tid = layout.tenant_id
        net = layout.docker_network_name
        api_key_env = f"TENANT_{tid.upper().replace('-', '_')}_TEIID_API_KEY"

        return f"""# Generated by Tablescope tenant data-plane provisioner.
# Tenant: {tid}
# Do NOT edit by hand — regenerate via the platform API.
services:
  {layout.teiid_container_name}:
    image: {self._image}
    container_name: {layout.teiid_container_name}
    restart: unless-stopped
    # No privileged mode; Docker socket is never mounted.
    security_opt:
      - no-new-privileges:true
    networks:
      {net}:
        ipv4_address: {layout.teiid_container_ip}
    ports:
      # Bound to localhost only — the platform API reaches these locally.
      - "127.0.0.1:{layout.host_servlet_port}:{8080}"
      - "127.0.0.1:{layout.host_pg_port}:{35432}"
      - "127.0.0.1:{layout.host_mgmt_port}:{9990}"
    volumes:
      - {layout.vdb_host_path}:/opt/wildfly/teiidfiles/customers:rw
      - {layout.logs_host_path}:/opt/wildfly/standalone/log:rw
    environment:
      TENANT_ID: "{tid}"
      TEIID_API_KEY: "${{{api_key_env}}}"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9990/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

networks:
  {net}:
    name: {net}
    driver: bridge
    ipam:
      config:
        - subnet: {layout.docker_subnet_cidr}
"""

    def directories(self, layout: TenantLayout) -> list[str]:
        """The directory tree that must exist for this tenant."""
        return [
            layout.tenant_root,
            layout.vdb_host_path,
            layout.logs_host_path,
            layout.secrets_host_path,
            layout.mounts_host_path,
            str(Path(layout.compose_host_path).parent),
        ]

    def generate(self, layout: TenantLayout, *, write: bool = False) -> GeneratedCompose:
        """Render the compose file; when ``write`` is true, materialize it.

        Writing requires the process to have permission to create the tenant
        directory tree (root/tablescope service user on the EC2 host). When the
        directories are not writable (e.g. inside the API container during
        tests) ``write`` should be left ``False`` and an operator/worker with
        host access performs the materialization.
        """
        content = self.render(layout)
        dirs = self.directories(layout)

        if write:
            for d in dirs:
                Path(d).mkdir(parents=True, exist_ok=True)
            # secrets dir must not be world/group readable
            os.chmod(layout.secrets_host_path, 0o700)
            compose_path = Path(layout.compose_host_path)
            compose_path.write_text(content, encoding="utf-8")

        return GeneratedCompose(
            tenant_id=layout.tenant_id,
            compose_path=layout.compose_host_path,
            content=content,
            directories=dirs,
        )
