"""Home AI Intelligence — diagnostic prompt suite over real project data.

For each accessible project, a fixed suite of diagnostic prompts runs against the
project's real data sources and documents and returns ``InsightCard`` dicts. The
analysis is deterministic and defensive: when a project lacks the data a prompt
needs (e.g. no financial table), that prompt is *skipped* rather than fabricated.
A lightweight cross-project synthesis runs over the prose summaries only — never
raw data — so project isolation is never breached.

The four built-in prompt types:
- ``risk_sla``            delivery lead-time vs SLA threshold  (bar chart)
- ``risk_expiry``         contracts expiring within 90 days    (document list)
- ``trend_spend``         actual vs budget / prior-period spend (kpi grid)
- ``opportunity_supplier`` top supplier performance / savings   (prose + callout)
"""
from app.services.analytical_method_engine import EngineMode, get_engine_mode
from app.services.analytical_method_engine import analyze as analyze_methods

from .card_builder import _card
from .card_ranking import (
    _ALLOWED_SEVERITIES,
    _SEVERITY_RANK,
    _card_priority,
    _dedupe_key,
    _normalize_severity,
    _pre_execution_dedupe,
    rank_and_dedupe_cards,
)
from .chart_builder import _build_chart, _build_multi_chart, _nice_name, _shape_scatter_label_col, _two_value_chart
from .chart_templates import (
    _SHAPE_TEMPLATE_MIN_FIT,
    _TEMPLATE_BUILDERS,
    _build_funnel_template,
    _build_heatmap_template,
    _build_radar_rows,
    _build_radar_template,
    _build_sankey_template,
    _build_scatter_template,
    _build_treemap_template,
)
from .claim_verification import _claim_step, _verify_card_claims
from .cross_reference import _cross_reference_sql, _humanize_column, _relationship_direction, _run_cross_reference
from .diagnostic_orchestration import (
    _DIAGNOSTIC_CARD_BUDGET_DEFAULT,
    _card_diagnostic_insights,
    _card_metric,
    _card_primary_table,
    _context_documents,
    _diagnostic_card_budget,
    _run_diagnostic,
)
from .diagnostic_prompts import (
    _BREACH_VALUES,
    _DATE_PATTERNS,
    _DATE_RE,
    _EXPIRY_KEYS,
    _FUTURE_DATE_KEYWORDS,
    _PROMPT_FUNCS,
    _STATUS_KEYWORDS,
    _THRESHOLD_KEYWORDS,
    _extract_expiry,
    _opportunity_supplier,
    _opportunity_top_performer,
    _parse_date,
    _risk_expiry,
    _risk_measure_vs_threshold,
    _risk_sla,
    _risk_status_breach,
    _risk_threshold,
    _risk_upcoming,
    _severity_for_rate,
    _trend_metric,
    _trend_spend,
    run_intelligence_suite,
)
from .formatting import (
    _COUNT_COL_RE,
    _CURRENCY_COL_RE,
    _ID_LABEL_RE,
    _PCT_COL_RE,
    _detect_value_format,
    _fmt_num,
    _fmt_value,
    _looks_like_id_labels,
    build_dashboard_narrative,
    build_widget_explanation,
    enhance_bar_readability,
)
from .method_driven_insights import _method_driven_insights
from .orchestrator import (
    ALL_PROMPT_TYPES,
    HOME_BEST_PRACTICES_FILE,
    home_best_practices,
    run_ai_intelligence,
    synthesise_cross_project,
)
from .query_helpers import (
    _AUDIT_PERIOD_EXCLUSIONS,
    _DIMENSION_COL_RE,
    _ENTITY_KEYWORDS,
    _KEY_SUFFIXES,
    _MEASURE_KEYWORDS,
    _PERIOD_KEYWORDS,
    _TARGET_COL_RE,
    _TWO_VALUE_TYPES,
    _YEAR_RE,
    QueryRunner,
    _agg_for_measure,
    _cardinality,
    _containment,
    _deep_analysis_sql,
    _detect_view_strict,
    _dimension_columns,
    _distinct_years,
    _enrich_period_keys,
    _extract_join_qualifiers,
    _find_table,
    _first_column,
    _first_time_column,
    _is_join_key,
    _is_period_column,
    _log_skip,
    _match_col,
    _measure_col,
    _norm,
    _now_iso,
    _period_columns_for_table,
    _period_expression,
    _period_grain,
    _period_label,
    _pick_columns,
    _pick_second_value,
    _query_with_error,
    _quote,
    _repair_fanned_out_join,
    _safe_query,
    _sample_values,
    _series_is_constant,
    _synthesize_templated_join,
    _tables_in_sql,
    _target_measure,
    _to_float,
    detect_entities,
    find_relationship_candidates,
    logger,
)
from .schema_context import (
    _PROJECT_COLORS,
    DocInfo,
    ProjectContext,
    ScopeLink,
    TableInfo,
    _resolve_scope_links,
    gather_project_context,
    project_color,
)
from .shape_template_insights import _shape_template_insights
from .widget_planning import (
    _CATEGORY_INTENT_HINTS,
    _attach_method_envelopes,
    _plan_documents,
    _resolve_intent_hint,
    plan_and_execute_widgets,
)

__all__ = [
    "ALL_PROMPT_TYPES",
    "EngineMode",
    "analyze_methods",
    "get_engine_mode",
    "DocInfo",
    "HOME_BEST_PRACTICES_FILE",
    "ProjectContext",
    "QueryRunner",
    "ScopeLink",
    "TableInfo",
    "_ALLOWED_SEVERITIES",
    "_AUDIT_PERIOD_EXCLUSIONS",
    "_BREACH_VALUES",
    "_CATEGORY_INTENT_HINTS",
    "_COUNT_COL_RE",
    "_CURRENCY_COL_RE",
    "_DATE_PATTERNS",
    "_DATE_RE",
    "_DIAGNOSTIC_CARD_BUDGET_DEFAULT",
    "_DIMENSION_COL_RE",
    "_ENTITY_KEYWORDS",
    "_EXPIRY_KEYS",
    "_FUTURE_DATE_KEYWORDS",
    "_ID_LABEL_RE",
    "_KEY_SUFFIXES",
    "_MEASURE_KEYWORDS",
    "_PCT_COL_RE",
    "_PERIOD_KEYWORDS",
    "_PROJECT_COLORS",
    "_PROMPT_FUNCS",
    "_SEVERITY_RANK",
    "_SHAPE_TEMPLATE_MIN_FIT",
    "_STATUS_KEYWORDS",
    "_TARGET_COL_RE",
    "_TEMPLATE_BUILDERS",
    "_THRESHOLD_KEYWORDS",
    "_TWO_VALUE_TYPES",
    "_YEAR_RE",
    "_agg_for_measure",
    "_attach_method_envelopes",
    "_build_chart",
    "_build_funnel_template",
    "_build_heatmap_template",
    "_build_multi_chart",
    "_build_radar_rows",
    "_build_radar_template",
    "_build_sankey_template",
    "_build_scatter_template",
    "_build_treemap_template",
    "_card",
    "_card_diagnostic_insights",
    "_card_metric",
    "_card_primary_table",
    "_card_priority",
    "_cardinality",
    "_claim_step",
    "_containment",
    "_context_documents",
    "_cross_reference_sql",
    "_dedupe_key",
    "_deep_analysis_sql",
    "_detect_value_format",
    "_detect_view_strict",
    "_diagnostic_card_budget",
    "_dimension_columns",
    "_distinct_years",
    "_enrich_period_keys",
    "_extract_expiry",
    "_extract_join_qualifiers",
    "_find_table",
    "_first_column",
    "_first_time_column",
    "_fmt_num",
    "_fmt_value",
    "_humanize_column",
    "_is_join_key",
    "_is_period_column",
    "_log_skip",
    "_looks_like_id_labels",
    "_match_col",
    "_measure_col",
    "_method_driven_insights",
    "_nice_name",
    "_norm",
    "_normalize_severity",
    "_now_iso",
    "_opportunity_supplier",
    "_opportunity_top_performer",
    "_parse_date",
    "_period_columns_for_table",
    "_period_expression",
    "_period_grain",
    "_period_label",
    "_pick_columns",
    "_pick_second_value",
    "_plan_documents",
    "_pre_execution_dedupe",
    "_query_with_error",
    "_quote",
    "_relationship_direction",
    "_repair_fanned_out_join",
    "_resolve_intent_hint",
    "_resolve_scope_links",
    "_risk_expiry",
    "_risk_measure_vs_threshold",
    "_risk_sla",
    "_risk_status_breach",
    "_risk_threshold",
    "_risk_upcoming",
    "_run_cross_reference",
    "_run_diagnostic",
    "_safe_query",
    "_sample_values",
    "_series_is_constant",
    "_severity_for_rate",
    "_shape_scatter_label_col",
    "_shape_template_insights",
    "_synthesize_templated_join",
    "_tables_in_sql",
    "_target_measure",
    "_to_float",
    "_trend_metric",
    "_trend_spend",
    "_two_value_chart",
    "_verify_card_claims",
    "build_dashboard_narrative",
    "build_widget_explanation",
    "detect_entities",
    "enhance_bar_readability",
    "find_relationship_candidates",
    "gather_project_context",
    "home_best_practices",
    "logger",
    "plan_and_execute_widgets",
    "project_color",
    "rank_and_dedupe_cards",
    "run_ai_intelligence",
    "run_intelligence_suite",
    "synthesise_cross_project",
]
