"""Compiled executable method data blocks."""

from __future__ import annotations

SCIPY = ["scipy"]


STATSMODELS = ["scipy", "statsmodels"]


NUMPY = ["numpy"]


def _card(use_when, dont, checks, fallback, output):
    return {
        "use_when": use_when,
        "do_not_use_when": dont,
        "required_checks": checks,
        "fallback": fallback,
        "output": output,
    }


EXECUTABLE = [
    {
        "method_id": "describe_numeric",
        "display_name": "Descriptive statistics + distribution profile",
        "category": "Data Profiling and Descriptive Statistics",
        "subcategory": "Dataset-level profiling",
        "executor_key": "describe_numeric",
        "dependencies": SCIPY,
        "supported_intents": ["describe_numeric"],
        "selection_rules": ["Exactly one numeric field requested"],
        "rejection_rules": ["No numeric field present"],
        "required_checks": ["n count", "null rate"],
        "fallback_methods": ["robust_descriptive_statistics"],
        "output_contract": {
            "fields": ["n", "mean", "median", "std", "min", "max",
                       "quantiles", "skewness", "kurtosis"]
        },
        "card": _card(
            ["A single numeric field needs summarizing"],
            ["The field is categorical or an identifier"],
            ["n count", "null rate", "distribution shape"],
            ["Robust statistics (median, IQR, MAD)"],
            ["mean", "median", "std", "quantiles", "skew", "kurtosis"],
        ),
    },
    {
        "method_id": "pearson_correlation",
        "display_name": "Pearson correlation + OLS regression",
        "category": "Correlation and Association Analysis",
        "subcategory": "Numeric-to-numeric",
        "executor_key": "pearson_correlation",
        "dependencies": STATSMODELS,
        "supported_intents": ["relationship_numeric"],
        "selection_rules": [
            "Two numeric continuous fields",
            "Relationship appears linear",
            "Outliers are low",
            "Sample size is sufficient",
            "Observations are independent",
        ],
        "rejection_rules": [
            "Relationship is nonlinear or only monotonic",
            "Heavy outliers exist",
            "Data is ordinal",
            "Strong missing-data bias exists",
        ],
        "required_checks": ["n count", "null rate", "outlier rate",
                            "normality/residual check", "leverage/influence check"],
        "fallback_methods": ["spearman_rank_correlation", "kendalls_tau"],
        "output_contract": {
            "fields": ["effect", "effectName", "pValue", "rSquared",
                       "confidenceInterval", "slope", "intercept"]
        },
        "card": _card(
            ["Two numeric continuous fields", "Relationship appears linear",
             "Outliers are low", "Sample size is sufficient"],
            ["Relationship is nonlinear or only monotonic", "Heavy outliers exist",
             "Data is ordinal"],
            ["n count", "null rate", "outlier rate", "normality/residual check",
             "leverage/influence check"],
            ["Spearman correlation", "Kendall correlation", "Huber/Theil-Sen regression"],
            ["slope", "intercept", "correlation coefficient", "R^2", "p-value",
             "confidence interval", "outlier count", "assumption warnings"],
        ),
    },
    {
        "method_id": "spearman_rank_correlation",
        "display_name": "Spearman rank correlation + robust regression",
        "category": "Correlation and Association Analysis",
        "subcategory": "Numeric-to-numeric",
        "executor_key": "spearman_correlation",
        "dependencies": SCIPY,
        "supported_intents": ["relationship_monotonic", "relationship_numeric"],
        "selection_rules": ["Ordinal or continuous", "Monotonic relationship",
                            "Non-normal or outlier-prone"],
        "rejection_rules": ["Relationship is non-monotonic"],
        "required_checks": ["n count", "null rate", "monotonicity"],
        "fallback_methods": ["kendalls_tau"],
        "output_contract": {"fields": ["effect", "effectName", "pValue", "confidenceInterval"]},
        "card": _card(
            ["Ordinal or continuous fields", "Monotonic relationship",
             "Non-normal or outlier-prone data"],
            ["Relationship is non-monotonic"],
            ["n count", "null rate", "monotonicity"],
            ["Kendall's tau"],
            ["spearman rho", "p-value", "confidence interval"],
        ),
    },
    {
        "method_id": "kendalls_tau",
        "display_name": "Kendall's tau correlation",
        "category": "Correlation and Association Analysis",
        "subcategory": "Numeric-to-numeric",
        "executor_key": "kendall_correlation",
        "dependencies": SCIPY,
        "supported_intents": ["relationship_monotonic"],
        "selection_rules": ["Ordinal", "Small samples", "Many ties", "Monotonic relationships"],
        "rejection_rules": ["Large samples where Spearman suffices"],
        "required_checks": ["n count", "null rate"],
        "fallback_methods": ["spearman_rank_correlation"],
        "output_contract": {"fields": ["effect", "effectName", "pValue"]},
        "card": _card(
            ["Ordinal data", "Small samples", "Many ties"],
            ["Non-monotonic relationship"],
            ["n count", "null rate"],
            ["Spearman correlation"],
            ["kendall tau", "p-value"],
        ),
    },
    {
        "method_id": "one_sample_t_test",
        "display_name": "One-sample t-test",
        "category": "Statistical Significance Testing",
        "subcategory": "One-sample tests",
        "executor_key": "one_sample_t_test",
        "dependencies": SCIPY,
        "supported_intents": ["compare_to_target"],
        "selection_rules": ["One numeric field", "Fixed comparison target",
                            "Approximately normal or n large"],
        "rejection_rules": ["Heavily skewed with small n"],
        "required_checks": ["n count", "null rate", "normality check"],
        "fallback_methods": ["wilcoxon_signed_rank_test", "sign_test"],
        "output_contract": {"fields": ["effect", "effectName", "pValue",
                                       "confidenceInterval", "cohensD"]},
        "card": _card(
            ["One numeric field compared to a fixed target",
             "Approximately normal or large n"],
            ["Heavily skewed with small n"],
            ["n count", "null rate", "normality check"],
            ["Wilcoxon signed-rank test", "Sign test"],
            ["mean difference", "p-value", "confidence interval", "Cohen's d"],
        ),
    },
    {
        "method_id": "welch_t_test",
        "display_name": "Welch's t-test (two independent groups)",
        "category": "Statistical Significance Testing",
        "subcategory": "Two independent samples",
        "executor_key": "welch_t_test",
        "dependencies": SCIPY,
        "supported_intents": ["compare_two_groups"],
        "selection_rules": ["Numeric outcome", "Binary independent group",
                            "Unequal variances tolerated"],
        "rejection_rules": ["Paired observations", "Heavily non-normal small samples"],
        "required_checks": ["n count", "null rate", "normality check"],
        "fallback_methods": ["mann_whitney_u_test", "permutation_test"],
        "output_contract": {"fields": ["effect", "effectName", "pValue",
                                       "confidenceInterval", "cohensD"]},
        "card": _card(
            ["Numeric outcome split by a binary group", "Independent samples"],
            ["Paired observations", "Heavily non-normal small samples"],
            ["n count per group", "null rate", "normality check"],
            ["Mann-Whitney U", "Permutation test"],
            ["mean difference", "p-value", "confidence interval", "Cohen's d"],
        ),
    },
    {
        "method_id": "students_t_test",
        "display_name": "Student's independent t-test",
        "category": "Statistical Significance Testing",
        "subcategory": "Two independent samples",
        "executor_key": "students_t_test",
        "dependencies": SCIPY,
        "supported_intents": ["compare_two_groups"],
        "selection_rules": ["Numeric outcome", "Binary group", "Equal variances"],
        "rejection_rules": ["Unequal variances", "Paired observations"],
        "required_checks": ["n count", "equal-variance check"],
        "fallback_methods": ["welch_t_test", "mann_whitney_u_test"],
        "output_contract": {"fields": ["effect", "pValue", "confidenceInterval", "cohensD"]},
        "card": _card(
            ["Numeric outcome, binary group, equal variances"],
            ["Unequal variances", "Paired data"],
            ["n count", "equal-variance check (Levene)"],
            ["Welch's t-test", "Mann-Whitney U"],
            ["mean difference", "p-value", "Cohen's d"],
        ),
    },
    {
        "method_id": "mann_whitney_u_test",
        "display_name": "Mann-Whitney U test",
        "category": "Statistical Significance Testing",
        "subcategory": "Two independent samples",
        "executor_key": "mann_whitney_u",
        "dependencies": SCIPY,
        "supported_intents": ["compare_two_groups"],
        "selection_rules": ["Numeric or ordinal outcome", "Binary group", "Non-normal"],
        "rejection_rules": ["Paired observations"],
        "required_checks": ["n count", "null rate"],
        "fallback_methods": ["welch_t_test"],
        "output_contract": {"fields": ["effect", "effectName", "pValue"]},
        "card": _card(
            ["Non-normal numeric/ordinal outcome by binary group"],
            ["Paired observations"],
            ["n count per group", "null rate"],
            ["Welch's t-test"],
            ["rank-biserial effect", "p-value"],
        ),
    },
    {
        "method_id": "paired_t_test",
        "display_name": "Paired t-test",
        "category": "Statistical Significance Testing",
        "subcategory": "Paired samples",
        "executor_key": "paired_t_test",
        "dependencies": SCIPY,
        "supported_intents": ["compare_paired"],
        "selection_rules": ["Two paired numeric measurements", "Approximately normal differences"],
        "rejection_rules": ["Independent groups", "Non-normal differences, small n"],
        "required_checks": ["n count", "normality of differences"],
        "fallback_methods": ["wilcoxon_signed_rank_test"],
        "output_contract": {"fields": ["effect", "pValue", "confidenceInterval", "cohensD"]},
        "card": _card(
            ["Two paired numeric measurements", "Normal differences"],
            ["Independent groups"],
            ["n count", "normality of differences"],
            ["Wilcoxon signed-rank test"],
            ["mean difference", "p-value", "Cohen's d"],
        ),
    },
    {
        "method_id": "wilcoxon_signed_rank_test",
        "display_name": "Wilcoxon signed-rank test",
        "category": "Statistical Significance Testing",
        "subcategory": "Paired samples",
        "executor_key": "wilcoxon_signed_rank",
        "dependencies": SCIPY,
        "supported_intents": ["compare_paired", "compare_to_target"],
        "selection_rules": ["Paired numeric/ordinal", "Non-normal differences"],
        "rejection_rules": ["Independent groups"],
        "required_checks": ["n count"],
        "fallback_methods": ["sign_test"],
        "output_contract": {"fields": ["effect", "pValue"]},
        "card": _card(
            ["Paired numeric/ordinal, non-normal differences"],
            ["Independent groups"],
            ["n count"],
            ["Sign test"],
            ["statistic", "p-value"],
        ),
    },
    {
        "method_id": "one_way_anova",
        "display_name": "One-way ANOVA",
        "category": "Statistical Significance Testing",
        "subcategory": "Three or more independent groups",
        "executor_key": "one_way_anova",
        "dependencies": SCIPY,
        "supported_intents": ["compare_multiple_groups"],
        "selection_rules": ["Numeric outcome", "3+ groups", "Equal variances", "Normal residuals"],
        "rejection_rules": ["Unequal variances", "Non-normal small samples"],
        "required_checks": ["n count", "equal-variance check", "normality check"],
        "fallback_methods": ["welch_anova", "kruskal_wallis_test"],
        "output_contract": {"fields": ["effect", "effectName", "pValue", "etaSquared"]},
        "card": _card(
            ["Numeric outcome across 3+ groups", "Equal variances, normal residuals"],
            ["Unequal variances", "Non-normal small samples"],
            ["n per group", "equal-variance check", "normality check"],
            ["Welch ANOVA", "Kruskal-Wallis"],
            ["F statistic", "p-value", "eta squared"],
        ),
    },
    {
        "method_id": "welch_anova",
        "display_name": "Welch ANOVA",
        "category": "Statistical Significance Testing",
        "subcategory": "Three or more independent groups",
        "executor_key": "welch_anova",
        "dependencies": STATSMODELS,
        "supported_intents": ["compare_multiple_groups"],
        "selection_rules": ["Numeric outcome", "3+ groups", "Unequal variances"],
        "rejection_rules": ["Non-normal small samples"],
        "required_checks": ["n count", "normality check"],
        "fallback_methods": ["kruskal_wallis_test"],
        "output_contract": {"fields": ["effect", "pValue"]},
        "card": _card(
            ["Numeric outcome across 3+ groups", "Unequal variances"],
            ["Non-normal small samples"],
            ["n per group", "normality check"],
            ["Kruskal-Wallis"],
            ["F statistic", "p-value"],
        ),
    },
    {
        "method_id": "kruskal_wallis_test",
        "display_name": "Kruskal-Wallis test",
        "category": "Statistical Significance Testing",
        "subcategory": "Three or more independent groups",
        "executor_key": "kruskal_wallis",
        "dependencies": SCIPY,
        "supported_intents": ["compare_multiple_groups"],
        "selection_rules": ["Numeric/ordinal outcome", "3+ groups", "Non-normal"],
        "rejection_rules": ["Repeated measures"],
        "required_checks": ["n count"],
        "fallback_methods": ["one_way_anova"],
        "output_contract": {"fields": ["effect", "pValue"]},
        "card": _card(
            ["Non-normal numeric/ordinal outcome across 3+ groups"],
            ["Repeated measures"],
            ["n per group"],
            ["One-way ANOVA"],
            ["H statistic", "p-value"],
        ),
    },
    {
        "method_id": "chi_square_test_of_independence",
        "display_name": "Chi-square test of independence",
        "category": "Correlation and Association Analysis",
        "subcategory": "Categorical-to-categorical",
        "executor_key": "chi_square_independence",
        "dependencies": SCIPY,
        "supported_intents": ["compare_category_rates"],
        "selection_rules": ["Two categorical fields", "Expected cell counts >= 5"],
        "rejection_rules": ["Sparse table with low expected counts"],
        "required_checks": ["n count", "expected cell counts"],
        "fallback_methods": ["fishers_exact_test"],
        "output_contract": {"fields": ["effect", "effectName", "pValue"]},
        "card": _card(
            ["Two categorical fields", "Expected cell counts >= 5"],
            ["Sparse table with low expected counts"],
            ["n count", "expected cell counts"],
            ["Fisher's exact test"],
            ["chi-square", "Cramer's V", "p-value"],
        ),
    },
    {
        "method_id": "fishers_exact_test",
        "display_name": "Fisher's exact test",
        "category": "Correlation and Association Analysis",
        "subcategory": "Categorical-to-categorical",
        "executor_key": "fisher_exact",
        "dependencies": SCIPY,
        "supported_intents": ["compare_category_rates"],
        "selection_rules": ["2x2 categorical table", "Small or sparse counts"],
        "rejection_rules": ["Table larger than 2x2"],
        "required_checks": ["n count"],
        "fallback_methods": ["chi_square_test_of_independence"],
        "output_contract": {"fields": ["effect", "effectName", "pValue"]},
        "card": _card(
            ["2x2 categorical table, small/sparse counts"],
            ["Table larger than 2x2"],
            ["n count"],
            ["Chi-square test"],
            ["odds ratio", "p-value"],
        ),
    },
    {
        "method_id": "multiple_linear_regression",
        "display_name": "Multiple linear regression (OLS)",
        "category": "Regression Methods",
        "subcategory": "Standard continuous-outcome regression",
        "executor_key": "linear_regression",
        "dependencies": STATSMODELS,
        "supported_intents": ["continuous_prediction", "explain_change"],
        "selection_rules": ["Numeric target", "One or more predictors", "Approximately linear"],
        "rejection_rules": ["Non-linear relationships", "Severe collinearity"],
        "required_checks": ["n count", "collinearity (VIF)", "homoscedasticity", "residual normality"],
        "fallback_methods": ["huber_regression", "ridge_regression"],
        "output_contract": {"fields": ["rSquared", "adjRSquared", "coefficients",
                                       "pValues", "confidenceInterval"]},
        "card": _card(
            ["Numeric target with numeric predictors", "Approximately linear"],
            ["Non-linear relationships", "Severe collinearity"],
            ["n per predictor", "VIF", "homoscedasticity", "residual normality"],
            ["Huber regression", "Ridge regression"],
            ["R^2", "adjusted R^2", "coefficients", "p-values", "confidence intervals"],
        ),
    },
    {
        "method_id": "binary_logistic_regression",
        "display_name": "Binary logistic regression",
        "category": "Regression Methods",
        "subcategory": "Generalized linear models",
        "executor_key": "logistic_regression",
        "dependencies": STATSMODELS,
        "supported_intents": ["binary_outcome"],
        "selection_rules": ["Binary target", "One or more predictors"],
        "rejection_rules": ["Multiclass target", "Perfect separation"],
        "required_checks": ["n count", "class balance", "collinearity (VIF)"],
        "fallback_methods": ["decision_tree"],
        "output_contract": {"fields": ["coefficients", "oddsRatios", "pValues", "pseudoRSquared"]},
        "card": _card(
            ["Binary target with predictors"],
            ["Multiclass target", "Perfect separation"],
            ["n count", "class balance", "VIF"],
            ["Decision tree with explanation"],
            ["coefficients", "odds ratios", "p-values", "pseudo R^2"],
        ),
    },
    {
        "method_id": "poisson_regression",
        "display_name": "Poisson regression",
        "category": "Regression Methods",
        "subcategory": "Generalized linear models",
        "executor_key": "poisson_regression",
        "dependencies": STATSMODELS,
        "supported_intents": ["count_outcome"],
        "selection_rules": ["Count target", "Mean approximately equals variance"],
        "rejection_rules": ["Overdispersion", "Excess zeros"],
        "required_checks": ["n count", "overdispersion check"],
        "fallback_methods": ["negative_binomial_regression"],
        "output_contract": {"fields": ["coefficients", "rateRatios", "pValues"]},
        "card": _card(
            ["Count target, mean ~ variance"],
            ["Overdispersion", "Excess zeros"],
            ["n count", "overdispersion check"],
            ["Negative-binomial regression"],
            ["coefficients", "rate ratios", "p-values"],
        ),
    },
    {
        "method_id": "negative_binomial_regression",
        "display_name": "Negative-binomial regression",
        "category": "Regression Methods",
        "subcategory": "Generalized linear models",
        "executor_key": "negative_binomial_regression",
        "dependencies": STATSMODELS,
        "supported_intents": ["count_outcome", "zero_heavy_count"],
        "selection_rules": ["Overdispersed count target"],
        "rejection_rules": ["Excess structural zeros needing hurdle model"],
        "required_checks": ["n count", "overdispersion check"],
        "fallback_methods": ["poisson_regression"],
        "output_contract": {"fields": ["coefficients", "rateRatios", "pValues"]},
        "card": _card(
            ["Overdispersed count target"],
            ["Excess structural zeros"],
            ["n count", "overdispersion check"],
            ["Poisson regression", "Zero-inflated/hurdle model"],
            ["coefficients", "rate ratios", "p-values"],
        ),
    },
    {
        "method_id": "ols_trend_slope",
        "display_name": "OLS trend slope",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Trend and seasonality tests",
        "executor_key": "trend_slope",
        "dependencies": STATSMODELS,
        "supported_intents": ["detect_trend"],
        "selection_rules": ["Ordered time index", "Numeric measure"],
        "rejection_rules": ["Strong seasonality dominating trend"],
        "required_checks": ["n count", "autocorrelation"],
        "fallback_methods": ["mann_kendall_trend_test", "sens_slope"],
        "output_contract": {"fields": ["slope", "pValue", "rSquared", "confidenceInterval"]},
        "card": _card(
            ["Ordered time index with a numeric measure"],
            ["Strong seasonality dominating the trend"],
            ["n count", "autocorrelation"],
            ["Mann-Kendall trend test", "Sen's slope"],
            ["slope", "p-value", "R^2", "confidence interval"],
        ),
    },
    {
        "method_id": "mann_kendall_trend_test",
        "display_name": "Mann-Kendall trend test",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Trend and seasonality tests",
        "executor_key": "mann_kendall_trend",
        "dependencies": SCIPY,
        "supported_intents": ["detect_trend"],
        "selection_rules": ["Ordered time index", "Monotonic trend suspected", "Non-normal"],
        "rejection_rules": ["Strong seasonality"],
        "required_checks": ["n count"],
        "fallback_methods": ["sens_slope"],
        "output_contract": {"fields": ["effect", "pValue", "trend"]},
        "card": _card(
            ["Ordered time index, non-normal, monotonic trend suspected"],
            ["Strong seasonality"],
            ["n count"],
            ["Sen's slope"],
            ["tau", "p-value", "trend direction"],
        ),
    },
    {
        "method_id": "sens_slope",
        "display_name": "Sen's slope estimator",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Trend and seasonality tests",
        "executor_key": "sens_slope",
        "dependencies": SCIPY,
        "supported_intents": ["detect_trend"],
        "selection_rules": ["Ordered time index", "Robust slope needed"],
        "rejection_rules": ["Strong seasonality"],
        "required_checks": ["n count"],
        "fallback_methods": ["ols_trend_slope"],
        "output_contract": {"fields": ["slope", "confidenceInterval"]},
        "card": _card(
            ["Ordered time index, robust slope needed"],
            ["Strong seasonality"],
            ["n count"],
            ["OLS trend slope"],
            ["slope", "confidence interval"],
        ),
    },
    {
        "method_id": "shapiro_wilk_test",
        "display_name": "Shapiro-Wilk normality test",
        "category": "Distribution Analysis and Distribution Fitting",
        "subcategory": "Goodness-of-fit methods",
        "executor_key": "normality_test",
        "dependencies": SCIPY,
        "supported_intents": ["normality"],
        "selection_rules": ["One numeric field", "n between 3 and 5000"],
        "rejection_rules": ["n > 5000 (use Anderson-Darling)"],
        "required_checks": ["n count", "null rate"],
        "fallback_methods": ["anderson_darling_test", "dagostino_pearson_normality_test"],
        "output_contract": {"fields": ["statistic", "pValue", "isNormal"]},
        "card": _card(
            ["One numeric field, 3 <= n <= 5000"],
            ["Very large n"],
            ["n count", "null rate"],
            ["Anderson-Darling", "D'Agostino-Pearson"],
            ["W statistic", "p-value", "normal?"],
        ),
    },
    {
        "method_id": "stl_decomposition",
        "display_name": "STL seasonal-trend decomposition",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Decomposition and smoothing",
        "executor_key": "stl_decomposition",
        "dependencies": STATSMODELS,
        "supported_intents": ["trend_seasonality"],
        "selection_rules": ["Regular time series", "At least two full seasonal cycles"],
        "rejection_rules": ["Irregular spacing", "Too few periods"],
        "required_checks": ["n count", "regular spacing", "period detected"],
        "fallback_methods": ["ols_trend_slope"],
        "output_contract": {"fields": ["trendStrength", "seasonalStrength", "period"]},
        "card": _card(
            ["Regular time series with >= 2 seasonal cycles"],
            ["Irregular spacing", "Too few periods"],
            ["n count", "regular spacing", "period detected"],
            ["OLS trend slope"],
            ["trend strength", "seasonal strength", "period"],
        ),
    },
]


EXECUTABLE_R = [
    {
        "method_id": "period_change",
        "display_name": "Period-over-period change",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Business time-series comparison",
        "executor_key": "period_change",
        "execution_engine": "r",
        "dependencies": ["base R"],
        "supported_intents": ["compare_periods", "compare_year_over_year", "compare_to_baseline", "measure_rate_of_change"],
        "selection_rules": ["Ordered time index", "Numeric measure", "Two or more distinct periods"],
        "rejection_rules": ["No time column", "No numeric measure", "Only one period"],
        "required_checks": ["n count", "period detection", "zero/negative baseline guard"],
        "fallback_methods": [],
        "output_contract": {"fields": ["currentPeriod", "comparisonPeriod", "absoluteChange", "relativeChange", "percentagePointChange", "partialPeriod", "zeroBaselineGuard", "negativeBaselineWarning"]},
        "card": _card(
            ["Ordered time index", "Numeric measure", "Two or more periods to compare"],
            ["No time column", "No numeric measure", "Only one period"],
            ["n count", "period detection", "zero/negative baseline guard"],
            [],
            ["current period", "comparison period", "absolute change", "relative change", "percentage-point change", "partial-period flag"],
        ),
    },
    {
        "method_id": "detect_change_point",
        "display_name": "Change-point detection",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Business time-series comparison",
        "executor_key": "detect_change_point",
        "execution_engine": "r",
        "dependencies": ["changepoint"],
        "supported_intents": ["detect_change_point"],
        "selection_rules": ["Ordered time index", "Numeric measure", "Suspected structural break"],
        "rejection_rules": ["No time column", "No numeric measure", "Too few points"],
        "required_checks": ["n count", "regular spacing"],
        "fallback_methods": [],
        "output_contract": {"fields": ["changePointIndex", "changePointDate", "segmentMeanBefore", "segmentMeanAfter", "confidence"]},
        "card": _card(
            ["Ordered time index", "Numeric measure", "Suspected structural break"],
            ["No time column", "No numeric measure", "Too few ordered points"],
            ["n count", "regular spacing"],
            [],
            ["change-point index/date", "segment means before/after", "confidence"],
        ),
    },
    {
        "method_id": "detect_anomalies",
        "display_name": "Anomaly detection",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Business time-series comparison",
        "executor_key": "detect_anomalies",
        "execution_engine": "r",
        "dependencies": ["forecast"],
        "supported_intents": ["detect_anomalies"],
        "selection_rules": ["Ordered time index", "Numeric measure", "Expected band + outliers"],
        "rejection_rules": ["No time column", "No numeric measure"],
        "required_checks": ["n count", "regular spacing"],
        "fallback_methods": [],
        "output_contract": {"fields": ["expected", "lower", "upper", "anomalies", "anomalyCount"]},
        "card": _card(
            ["Ordered time index", "Numeric measure", "Need expected band and outliers"],
            ["No time column", "No numeric measure"],
            ["n count", "regular spacing"],
            [],
            ["expected value", "prediction interval", "flagged anomalies"],
        ),
    },
    {
        "method_id": "forecast_time_series",
        "display_name": "Time-series forecast",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Business time-series comparison",
        "executor_key": "forecast_time_series",
        "execution_engine": "r",
        "dependencies": ["forecast"],
        "supported_intents": ["forecast_time_series"],
        "selection_rules": ["Ordered time index", "Numeric measure", "Sufficient history for forecast"],
        "rejection_rules": ["No time column", "No numeric measure", "Too few periods"],
        "required_checks": ["n count", "regular spacing"],
        "fallback_methods": [],
        "output_contract": {"fields": ["pointForecast", "lower", "upper", "horizon", "method"]},
        "card": _card(
            ["Ordered time index", "Numeric measure", "Sufficient history"],
            ["No time column", "No numeric measure", "Too few periods"],
            ["n count", "regular spacing"],
            [],
            ["point forecast", "prediction interval", "forecast horizon"],
        ),
    },
    {
        "method_id": "contribution_to_change",
        "display_name": "Contribution to change",
        "category": "Time-Series Analysis and Forecasting",
        "subcategory": "Business time-series comparison",
        "executor_key": "contribution_to_change",
        "execution_engine": "r",
        "dependencies": ["base R"],
        "supported_intents": ["contribution_to_change"],
        "selection_rules": ["Numeric measure", "Categorical grouping", "Two periods or ordered time"],
        "rejection_rules": ["No grouping", "No numeric measure"],
        "required_checks": ["n count", "group cardinality"],
        "fallback_methods": [],
        "output_contract": {"fields": ["group", "contribution", "contributionPercent", "rank"]},
        "card": _card(
            ["Numeric measure", "Categorical grouping", "Two periods or ordered time"],
            ["No grouping", "No numeric measure"],
            ["n count", "group cardinality"],
            [],
            ["per-group contribution", "percentage of total change", "rank"],
        ),
    },
]
