<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  
    <modelVersion>4.0.0</modelVersion>
    <groupId>cloud.tablescope</groupId>
    <artifactId>project-TeiidExcelImporter</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    
    <dependencies>
        <dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20240303</version>
		</dependency>
		<dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
        </dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.1.0-alpha1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
            </exclusions>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.12.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.1</version>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-client</artifactId>
			<version>16.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-api</artifactId>
			<version>16.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-runtime</artifactId>
			<version>16.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-engine</artifactId>
			<version>12.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-common-core</artifactId>
			<version>16.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-jboss-admin</artifactId>
			<version>11.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.teiid</groupId>
			<artifactId>teiid-jdbc</artifactId>
			<version>8.12.18.6_4-redhat-64-3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.teiid</groupId>
                    <artifactId>teiid-jdbc</artifactId>
                </exclusion>
            </exclusions>
		</dependency>
		<dependency>
			<groupId>org.teiid</groupId>
			<artifactId>teiid-admin</artifactId>
			<version>12.3.2</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.xnio</groupId>
			<artifactId>xnio-nio</artifactId>
			<version>3.8.7.Final</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.xnio</groupId>
			<artifactId>xnio-api</artifactId>
			<version>3.8.7.Final</version>
		</dependency>
		<dependency>
			<groupId>org.wildfly.common</groupId>
			<artifactId>wildfly-common</artifactId>
			<version>1.6.0.Final</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.2</version>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.2-1002-jdbc4</version>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-csv</artifactId>
			<version>1.8</version>
		</dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>javax.servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>cloud.tablescope.TeiidExcelImporter</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version> <!-- Adjust version as needed -->
				<configuration>
					<!-- Optional: Set the name of the WAR file -->
					<warName>TeiidExcelImporter</warName>
				</configuration>
			</plugin>
        </plugins>
    </build>
    
    <!-- Repository for teiid-jdbc -->
    <repositories>
        <repository>
            <id>redhat-ga-repository</id>
            <name>Red Hat GA Repository</name>
            <url>https://maven.repository.redhat.com/ga/</url>
        </repository>
	</repositories>
</project>
