/**
 * Central chart registry.
 *
 * A single source of truth describing each chart family: the variants it
 * supports, the option fields the editor should expose, default option
 * values, the fields it requires, and the AI selection rules. The dashboard
 * widget editor, the option panel, config validation, and AI dashboard
 * generation all read from this registry so the chart catalog stays
 * consistent and easy to extend.
 */

import type { WidgetType, VisualizationOptions } from "@/components/dashboard/types";import { ChartTypeDefinition } from "./chart-type-definition";
import { COLOR_SCHEME_OPTION } from "./color-scheme-option";
import { LINE_OPTIONS } from "./line-options";
import { AREA_OPTIONS } from "./area-options";
import { BAR_OPTIONS } from "./bar-options";
import { COMPOSED_OPTIONS } from "./composed-options";
import { PIE_OPTIONS } from "./pie-options";
import { SCATTER_OPTIONS } from "./scatter-options";
import { HEATMAP_OPTIONS } from "./heatmap-options";
import { RADAR_OPTIONS } from "./radar-options";
import { RADIAL_BAR_OPTIONS } from "./radial-bar-options";
import { TREEMAP_OPTIONS } from "./treemap-options";
import { FUNNEL_OPTIONS } from "./funnel-options";
import { SANKEY_OPTIONS } from "./sankey-options";
import { SUNBURST_OPTIONS } from "./sunburst-options";
import { TREE_OPTIONS } from "./tree-options";
import { GRAPH_OPTIONS } from "./graph-options";
import { PARALLEL_OPTIONS } from "./parallel-options";
import { LINES_OPTIONS } from "./lines-options";
import { CANDLESTICK_OPTIONS } from "./candlestick-options";
import { BOXPLOT_OPTIONS } from "./boxplot-options";
import { PICTORIAL_BAR_OPTIONS } from "./pictorial-bar-options";
import { THEME_RIVER_OPTIONS } from "./theme-river-options";
import { MAP_OPTIONS } from "./map-options";



export const CHART_REGISTRY: Partial<Record<WidgetType, ChartTypeDefinition>> = {
  kpi: {
    type: "kpi",
    label: "KPI",
    family: "kpi",
    icon: "\u{1F522}",
    description: "A single headline metric.",
    requiredFields: ["y"],
    variants: [],
    options: [],
    bestFor: ["One important metric"],
    aiRules: ["Use KPI Card for one important metric."],
  },
  table: {
    type: "table",
    label: "Table",
    family: "table",
    icon: "\u{1F4CB}",
    description: "Raw rows in a grid.",
    requiredFields: [],
    variants: [],
    options: [],
    bestFor: ["Detail records", "Fallback for unknown chart types"],
    aiRules: ["Use a table when detail rows matter or no chart fits."],
  },
  line: {
    type: "line",
    label: "Line",
    family: "line",
    icon: "\u{1F4C8}",
    description: "Trend over a continuous or time dimension.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Straight", defaultOptions: { curveType: "linear", lineStyle: "solid", dualAxis: false, tinyMode: false } },
      { value: "smooth_line", label: "Smooth", defaultOptions: { curveType: "monotone" } },
      { value: "step_line", label: "Step", defaultOptions: { curveType: "step" } },
      { value: "dashed_line", label: "Dashed", defaultOptions: { lineStyle: "dashed" } },
      { value: "biaxial_line", label: "Biaxial", defaultOptions: { dualAxis: true } },
      { value: "animated_line", label: "Animated", defaultOptions: { animate: true } },
      { value: "tiny_line", label: "Tiny", defaultOptions: { tinyMode: true } },
    ],
    options: LINE_OPTIONS,
    bestFor: ["Time trend", "SLA / cost / volume over time"],
    aiRules: [
      "Use Line for time trend.",
      "Add a reference line for a target/threshold.",
    ],
  },
  area: {
    type: "area",
    label: "Area",
    family: "area",
    icon: "\u{1F4C9}",
    description: "Cumulative or volume trend.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Area", defaultOptions: { stackMode: "none" } },
      { value: "stacked_area", label: "Stacked", defaultOptions: { stackMode: "stacked" } },
    ],
    options: AREA_OPTIONS,
    bestFor: ["Cumulative trend", "Volume over time"],
    aiRules: ["Use Area for cumulative or volume trend."],
  },
  bar: {
    type: "bar",
    label: "Bar",
    family: "bar",
    icon: "\u{1F4CA}",
    description: "Compare values across categories.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "column", label: "Column", defaultOptions: { barLayout: "vertical", stackMode: "none" } },
      { value: "stacked_bar", label: "Stacked", defaultOptions: { barLayout: "vertical", stackMode: "stacked" } },
      { value: "grouped_bar", label: "Grouped", defaultOptions: { barLayout: "vertical", stackMode: "none" } },
      { value: "horizontal_bar", label: "Horizontal", defaultOptions: { barLayout: "horizontal", stackMode: "none" } },
      { value: "stacked_horizontal", label: "Stacked Horiz.", defaultOptions: { barLayout: "horizontal", stackMode: "stacked" } },
      { value: "positive_negative", label: "Pos / Neg", defaultOptions: { barLayout: "vertical", colorBySign: true } },
      { value: "waterfall", label: "Waterfall", defaultOptions: { barLayout: "vertical", cumulative: true } },
      { value: "population_pyramid", label: "Pyramid", defaultOptions: { barLayout: "horizontal" } },
    ],
    options: BAR_OPTIONS,
    bestFor: ["Category comparison", "Top-N rankings (horizontal)"],
    aiRules: [
      "Use Bar for category comparison.",
      "Use Horizontal Bar for Top-N rankings.",
      "Use Stacked Bar for category breakdown across a group.",
      "Use Grouped Bar for side-by-side comparison.",
    ],
  },
  combo: {
    type: "combo",
    label: "Combo",
    family: "composed",
    icon: "\u{1F4CA}\u{1F4C8}",
    description: "Bars plus an overlaid line, often dual-axis.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "bar_line", label: "Bar + Line", defaultOptions: { dualAxis: true } },
      { value: "dual_line", label: "Dual Line", defaultOptions: { dualAxis: true } },
    ],
    options: COMPOSED_OPTIONS,
    bestFor: ["Count plus rate", "Actual plus target"],
    aiRules: ["Use Combo for count plus rate, or actual plus target."],
  },
  pie: {
    type: "pie",
    label: "Pie",
    family: "pie",
    icon: "\u{1F369}",
    description: "Part-to-whole distribution.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Pie", defaultOptions: { innerRadius: 0, startAngle: 90, endAngle: -270 } },
      { value: "donut", label: "Donut", defaultOptions: { innerRadius: 55, startAngle: 90, endAngle: -270 } },
      { value: "two_level", label: "Two-level", defaultOptions: { innerRadius: 45 } },
      { value: "gauge", label: "Gauge", defaultOptions: { innerRadius: 55, startAngle: 180, endAngle: 0, groupSmallSlices: false } },
    ],
    options: PIE_OPTIONS,
    bestFor: ["Small part-to-whole distribution (<= 7 categories)"],
    aiRules: [
      "Use Donut/Pie for small part-to-whole distribution under 7 categories.",
      "Group small slices into 'Other' when there are many categories.",
    ],
  },
  scatter: {
    type: "scatter",
    label: "Scatter / Bubble",
    family: "scatter",
    icon: "\u{1F4A0}",
    description: "Correlation between two numeric measures; bubble adds a third.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Scatter", defaultOptions: { bubble: false, showTrendLine: false } },
      { value: "bubble", label: "Bubble", defaultOptions: { bubble: true } },
      { value: "best_fit", label: "Best fit", defaultOptions: { showTrendLine: true } },
    ],
    options: SCATTER_OPTIONS,
    bestFor: ["Cost vs utilization", "Age vs risk", "Correlation analysis"],
    aiRules: ["Use Scatter/Bubble for correlation between numeric measures."],
  },
  radar: {
    type: "radar",
    label: "Radar",
    family: "radar",
    icon: "\u{1F578}\u{FE0F}",
    description: "Compare multiple dimensions for one or more entities.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Radar" },
      { value: "scorecard", label: "Scorecard" },
    ],
    options: RADAR_OPTIONS,
    bestFor: ["Supplier scorecard", "Service health", "Maturity comparison"],
    aiRules: ["Use Radar when comparing multiple dimensions for one or more entities."],
  },
  radial_bar: {
    type: "radial_bar",
    label: "Radial Bar",
    family: "radial_bar",
    icon: "\u{1F3AF}",
    description: "Percentage-to-target metrics drawn as concentric arcs.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Radial Bar" },
      { value: "multi_ring", label: "Multi-ring" },
    ],
    options: RADIAL_BAR_OPTIONS,
    bestFor: ["Patch / SLA compliance", "Budget utilization", "OEE"],
    aiRules: ["Use Radial Bar for percentage-to-target metrics."],
  },
  treemap: {
    type: "treemap",
    label: "Treemap",
    family: "treemap",
    icon: "\u{1F9E9}",
    description: "Hierarchical part-to-whole by rectangle area.",
    requiredFields: ["x", "y"],
    variants: [
      { value: "", label: "Treemap" },
      { value: "nested", label: "Nested" },
    ],
    options: TREEMAP_OPTIONS,
    bestFor: ["Cloud cost by service", "Spend by category", "Revenue by region"],
    aiRules: ["Use Treemap for hierarchical spend/value."],
  },
  funnel: {
    type: "funnel",
    label: "Funnel",
    family: "funnel",
    icon: "\u{1FA9D}",
    description: "Stage-by-stage progression of a count.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Funnel" }],
    options: FUNNEL_OPTIONS,
    bestFor: ["Ticket lifecycle", "Approval stages", "Pipeline"],
    aiRules: ["Use Funnel for stage progression."],
  },
  sankey: {
    type: "sankey",
    label: "Sankey",
    family: "sankey",
    icon: "\u{1F500}",
    description: "Flow from source to target categories, weighted by value.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Sankey" }],
    options: SANKEY_OPTIONS,
    bestFor: ["Source \u2192 service \u2192 group flows", "Provider \u2192 BU spend"],
    aiRules: ["Use Sankey for source-to-target flows."],
  },
  heatmap: {
    type: "heatmap",
    label: "Heatmap",
    family: "heatmap",
    icon: "\u{1F525}",
    description: "Density of a value across two categorical dimensions.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Heatmap" }],
    options: HEATMAP_OPTIONS,
    bestFor: ["Two-dimension breakdown", "Correlation matrix", "Volume by region and period"],
    aiRules: ["Use Heatmap when a value varies across two categorical dimensions."],
    enabled: true,
  },
  effect_scatter: {
    type: "effect_scatter",
    label: "Effect Scatter",
    family: "effect_scatter",
    icon: "\u{2728}",
    description: "Scatter with animated emphasis on each point.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Effect Scatter" }],
    options: SCATTER_OPTIONS,
    bestFor: ["Anomalies", "Highlights", "Time-point events"],
    aiRules: ["Use Effect Scatter to emphasize individual points."],
    enabled: true,
  },
  gauge: {
    type: "gauge",
    label: "Gauge",
    family: "gauge",
    icon: "\u{1F6E0}\u{FE0F}",
    description: "A single value shown as a radial gauge.",
    requiredFields: ["y"],
    variants: [
      { value: "", label: "Gauge" },
      { value: "semi", label: "Semi-circle" },
    ],
    options: [
      { key: "showTooltip", label: "Show tooltip", type: "boolean", group: "chart", defaultValue: true },
      { key: "domainMin", label: "Min value", type: "number", group: "advanced", defaultValue: 0, step: 1 },
      { key: "domainMax", label: "Max value", type: "number", group: "advanced", defaultValue: 100, step: 1 },
      { key: "innerRadius", label: "Inner radius %", type: "number", group: "style", defaultValue: 55, min: 0, max: 90, step: 5 },
      { key: "outerRadius", label: "Outer radius %", type: "number", group: "style", defaultValue: 80, min: 40, max: 100, step: 5 },
      COLOR_SCHEME_OPTION,
    ],
    bestFor: ["Current value vs target", "SLA", "Utilization"],
    aiRules: ["Use Gauge for a single current value against a known scale."],
    enabled: true,
  },
  sunburst: {
    type: "sunburst",
    label: "Sunburst",
    family: "sunburst",
    icon: "\u{1F31F}",
    description: "A radial hierarchical part-to-whole chart.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Sunburst" }],
    options: SUNBURST_OPTIONS,
    bestFor: ["Hierarchical part-to-whole", "Nested categories"],
    aiRules: ["Use Sunburst for nested hierarchical breakdowns."],
    enabled: true,
  },
  tree: {
    type: "tree",
    label: "Tree",
    family: "tree",
    icon: "\u{1F334}",
    description: "Branching hierarchy from a root node.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Tree" }],
    options: TREE_OPTIONS,
    bestFor: ["Org chart", "Nested categories", "Decision trees"],
    aiRules: ["Use Tree for branching hierarchical data."],
    enabled: true,
  },
  graph: {
    type: "graph",
    label: "Graph",
    family: "graph",
    icon: "\u{1F4DA}",
    description: "Nodes and edges showing relationships.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Graph" }],
    options: GRAPH_OPTIONS,
    bestFor: ["Network relationships", "Dependency maps"],
    aiRules: ["Use Graph when nodes are connected by a value."],
    enabled: true,
  },
  parallel: {
    type: "parallel",
    label: "Parallel Coordinates",
    family: "parallel",
    icon: "\u{1F4C9}",
    description: "Compare many numeric dimensions at once.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Parallel" }],
    options: PARALLEL_OPTIONS,
    bestFor: ["Multi-dimensional comparison", "Feature profiles"],
    aiRules: ["Use Parallel Coordinates for comparing many numeric dimensions."],
    enabled: true,
  },
  lines: {
    type: "lines",
    label: "Lines",
    family: "lines",
    icon: "\u{1F4E5}",
    description: "Connected line paths, useful for movement or flows.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Lines" }],
    options: LINES_OPTIONS,
    bestFor: ["Movement paths", "Origin-destination flows"],
    aiRules: ["Use Lines for origin-destination or movement paths."],
    enabled: true,
  },
  candlestick: {
    type: "candlestick",
    label: "Candlestick",
    family: "candlestick",
    icon: "\u{1F4C8}",
    description: "Open/high/low/close price data.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Candlestick" }],
    options: CANDLESTICK_OPTIONS,
    bestFor: ["OHLC price data", "Financial series"],
    aiRules: ["Use Candlestick for open/high/low/close data."],
    enabled: true,
  },
  boxplot: {
    type: "boxplot",
    label: "Boxplot",
    family: "boxplot",
    icon: "\u{1F4CA}",
    description: "Distribution summary with quartiles and outliers.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Boxplot" }],
    options: BOXPLOT_OPTIONS,
    bestFor: ["Distribution comparison", "Statistical summaries"],
    aiRules: ["Use Boxplot to compare distributions across categories."],
    enabled: true,
  },
  pictorial_bar: {
    type: "pictorial_bar",
    label: "Pictorial Bar",
    family: "pictorial_bar",
    icon: "\u{1F4A0}",
    description: "Bars rendered as symbols or icons.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Pictorial Bar" }],
    options: PICTORIAL_BAR_OPTIONS,
    bestFor: ["Ikonographic comparisons", "Category ranking"],
    aiRules: ["Use Pictorial Bar for category comparisons with icons."],
    enabled: true,
  },
  theme_river: {
    type: "theme_river",
    label: "Theme River",
    family: "theme_river",
    icon: "\u{1F3DE}\u{FE0F}",
    description: "Event or value streams over time.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Theme River" }],
    options: THEME_RIVER_OPTIONS,
    bestFor: ["Event streams", "Temporal themes"],
    aiRules: ["Use Theme River for value streams over a continuous axis."],
    enabled: true,
  },
  map: {
    type: "map",
    label: "Map",
    family: "map",
    icon: "\u{1F5FA}\u{FE0F}",
    description: "Geographic values by region.",
    requiredFields: ["x", "y"],
    variants: [{ value: "", label: "Map" }],
    options: MAP_OPTIONS,
    bestFor: ["Geographic distribution", "Regional metrics"],
    aiRules: ["Use Map for geographic region values."],
    enabled: true,
  },
};